# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 01:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 1, 2, 30, 512616, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='price_expiration',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 16, 1, 2, 30, 512646, tzinfo=utc)),
        ),
    ]
