# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171016_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfp',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='price_expiration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
