# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171016_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='price_expiration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
