# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171016_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='rfp',
            name='price_expiration',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
