# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request_for_quote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='request_for_quote.proto',
  package='protobuf',
  syntax='proto2',
  serialized_pb=_b('\n\x17request_for_quote.proto\x12\x08protobuf\"]\n\x03RFQ\x12\x10\n\x08quantity\x18\x01 \x02(\x05\x12\x12\n\naccount_id\x18\x02 \x02(\x05\x12\x16\n\x0eproduct_number\x18\x03 \x02(\x05\x12\x18\n\x10product_category\x18\x04 \x02(\x05\"i\n\x03RFP\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x02(\x05\x12\x12\n\naccount_id\x18\x03 \x02(\x05\x12\x16\n\x0eproduct_number\x18\x04 \x02(\x05\x12\x18\n\x10product_category\x18\x05 \x02(\t')
)




_RFQ = _descriptor.Descriptor(
  name='RFQ',
  full_name='protobuf.RFQ',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='quantity', full_name='protobuf.RFQ.quantity', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protobuf.RFQ.account_id', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_number', full_name='protobuf.RFQ.product_number', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_category', full_name='protobuf.RFQ.product_category', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=130,
)


_RFP = _descriptor.Descriptor(
  name='RFP',
  full_name='protobuf.RFP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.RFP.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='quantity', full_name='protobuf.RFP.quantity', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='account_id', full_name='protobuf.RFP.account_id', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_number', full_name='protobuf.RFP.product_number', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='product_category', full_name='protobuf.RFP.product_category', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=237,
)

DESCRIPTOR.message_types_by_name['RFQ'] = _RFQ
DESCRIPTOR.message_types_by_name['RFP'] = _RFP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RFQ = _reflection.GeneratedProtocolMessageType('RFQ', (_message.Message,), dict(
  DESCRIPTOR = _RFQ,
  __module__ = 'request_for_quote_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.RFQ)
  ))
_sym_db.RegisterMessage(RFQ)

RFP = _reflection.GeneratedProtocolMessageType('RFP', (_message.Message,), dict(
  DESCRIPTOR = _RFP,
  __module__ = 'request_for_quote_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.RFP)
  ))
_sym_db.RegisterMessage(RFP)


# @@protoc_insertion_point(module_scope)
